version: '{build}'
skip_tags: true
os: Windows Server 2012
image:
  - Visual Studio 2017
install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\maven" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'http://www.us.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip',
          'C:\maven-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\maven-bin.zip", "C:\maven")
      }
      Copy-Item .appveyor\settings.xml C:\Users\appveyor\.m2\settings.xml
  - cmd: gpg --import .appveyor\sec.asc
  - cmd: SET M3_HOME=C:\maven\apache-maven-3.5.0
  - cmd: SET M3=%M3_HOME%\bin
  - cmd: SET PATH=%M3%;%JAVA_HOME%\bin;%PATH%
build_script:
  - mvn clean package --batch-mode -DskipTests
test_script:
  - mvn clean test --batch-mode -Djna.nosys=true
deploy_script:
  - mvn clean deploy --batch-mode -DskipTests -DskipNexusStagingDeployMojo=false
on_failure:
  - ps: |
      7z a -r surefire-reports.zip '**\target\surefire-reports\*'
      Push-AppveyorArtifact surefire-reports.zip -DeploymentName 'Surefire Reports'
on_finish:
  - ps: |
      $url = "https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)"
      $wc = New-Object 'System.Net.WebClient'
      $dirs = Get-ChildItem -Filter surefire-reports -Recurse
      ForEach ($dir in $dirs)
      {
        $files = Get-ChildItem -Path $dir.FullName -Filter TEST-*.xml
        ForEach ($file in $files)
        {
          $wc.UploadFile($url, (Resolve-Path $file.FullName))
        }
      }
cache:
  - C:\maven\
  - C:\Users\appveyor\.m2